version: '3.8'
services:
  zeronexus:
    image: nginx:alpine
    container_name: zeronexus-website-issue19-dev
    ports:
      - "8083:80" # Port for issue-19 development
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./website:/usr/share/nginx/html:ro
    depends_on:
      - php
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped

  # PHP-FPM service with development extensions
  php:
    image: php:8.2-fpm-alpine
    container_name: zeronexus-php-issue19-dev
    volumes:
      - ./website:/usr/share/nginx/html:ro
    environment:
      - ENVIRONMENT=development
      - PHP_INI_DIR=/usr/local/etc/php
      - PHP_MEMORY_LIMIT=256M
      - DISPLAY_ERRORS=1
    restart: unless-stopped
    command: sh -c "docker-php-ext-install opcache && php-fpm"