version: '3.8'
services:
  zeronexus:
    image: nginx:alpine
    container_name: zeronexus-website
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./website:/usr/share/nginx/html:ro
    # Add dependency on PHP service
    depends_on:
      - php
    
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    restart: always
    
    labels:
      - "com.docker.compose.project=zeronexus"
      - "com.docker.compose.service=website"
      - "maintainer=zeronexus"
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # New PHP-FPM service
  php:
    image: php:8.2-fpm-alpine
    container_name: zeronexus-php
    volumes:
      - ./website:/usr/share/nginx/html:ro
    
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    
    restart: always
    
    labels:
      - "com.docker.compose.project=zeronexus"
      - "com.docker.compose.service=php"
      - "maintainer=zeronexus"
    
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s