services:
  zeronexus:
    image: nginx:alpine
    container_name: zeronexus-website-dev
    ports:
      - "8082:80" # Different port to avoid conflicts with production
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf:ro  # Use dev-specific config
      - ./website:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx  # Enable nginx logs for debugging
    depends_on:
      - php
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped

  # PHP-FPM service with development extensions
  php:
    image: php:8.2-fpm-alpine
    container_name: zeronexus-php-dev
    volumes:
      - ./website:/usr/share/nginx/html
      - ./logs/php:/var/log/php  # Enable PHP logs for debugging
    environment:
      - ENVIRONMENT=development
      - PHP_INI_DIR=/usr/local/etc/php
      - PHP_MEMORY_LIMIT=256M
      - DISPLAY_ERRORS=1
      - ERROR_REPORTING=E_ALL
      - LOG_ERRORS=1
    restart: unless-stopped
    command: sh -c "
      docker-php-ext-install opcache && 
      echo 'display_errors = On' > /usr/local/etc/php/conf.d/display-errors.ini && 
      echo 'error_reporting = E_ALL' >> /usr/local/etc/php/conf.d/display-errors.ini && 
      echo 'log_errors = On' >> /usr/local/etc/php/conf.d/display-errors.ini && 
      echo 'error_log = /var/log/php/error.log' >> /usr/local/etc/php/conf.d/display-errors.ini && 
      mkdir -p /var/log/php && 
      touch /var/log/php/error.log && 
      chmod 666 /var/log/php/error.log && 
      php-fpm"