name: Deploy Zero Nexus Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, zeronexus-website]
    
    steps:
    - name: Deploy application
      run: |
        cd /home/zero/zeronexus-website
        git pull origin main
        docker-compose build --no-cache
        docker-compose up -d
        
    - name: Verify deployment
      run: |
        sleep 5
        curl -f http://localhost:8081 || exit 1
        echo "Deployment successful!"